### ISSUE TITLE
Unable to scale map as of latest update

### ISSUE THREAD

**Issue by ned406** [leatrix/leatrix-maps#14]
I see in the update notes that this feature was removed. Can I ask why and request that it be put back? the ability to scale the map - especially the quest view map was one of the best features of the addon.

**Comment by leatrix** [comment]
Map scaling was removed because it taints the map.

Here is how to make your own addon which scales the map:

```
WorldMapFrame.ScrollContainer.GetCursorPosition = function(f)
	local x,y = MapCanvasScrollControllerMixin.GetCursorPosition(f)
	local s = WorldMapFrame:GetScale()
	return x/s, y/s
end

hooksecurefunc(WorldMapFrame, "SynchronizeDisplayState", function()
	if not WorldMapFrame:IsMaximized() then
		WorldMapFrame:SetScale(1) -- Set your maximised map scale here
	else
		WorldMapFrame:SetScale(1) -- Set your windowed map scale here
	end
end)
```

Enter that code into [Wow AddOn Creator](https://addon.bool.no/).  Change SetScale(1) to whatever you want the scale to be.  1 is 100%.  1.5 is 150%.  2 is 200%, etc.  You can set the scale separately for maximised and windowed maps.

You can enter any title you want (such as MyMapScaleThingy) then download the zip and extract it to your addons folder.  Reload your UI and your map should be scaled to your settings.

**Comment by Difjob** [comment]
I've got to second that you put this feature back in, the unlocked map frame and the scaling are the main reasons I use the addon, the rest is just fluff. I would like all the map features I need in a single addon and this addon did that before the last update.

Not sure what "taints the map" means because I've never had any issues with it. Whatever the issue is, people can just choose not to scale the map. It's not like the feature breaks anything so what's the harm in leaving it in?

**Comment by leatrix** [comment]
The scale feature is back in 9.2.21 but it's now a separate setting in the zoom section.  Enabling it will taint the map and this is highlighted in the help button for the zoom section.  Thanks for the feedback.

**Comment by Difjob** [comment]
Appreciate you adding the option back.

Could you fully explain what you mean when you say it taints the map? Do you just mean it stretches the image?

**Comment by ned406** [comment]
Thank you for bringing it back Leatrix, its appreciated.



> Appreciate you adding the option back.
> 
> Could you fully explain what you mean when you say it taints the map? Do you just mean it stretches the image?


I might be wrong but I think certain UI elements such as hovering over the map to highlight a zone do not properly work when they are scaled up/down because the elements dont scale with the map.

I personally use the Quest log version of the map rather than the big world map because I find it easier and better to use. Scaling has always worked fine on that, as for the bigger map I cant comment.

**Comment by leatrix** [comment]
There are 4 settings in LTM for Shadowlands which taint the map and these are all under the Zoom section (the help button explains that using any of the settings in the zoom section will taint the map).  So you can avoid map taint in LTM by not using the settings in the zoom section (remember zoom level, increase zoom level, center map on player and scale the map).

However, if you use other map addons such as HandyNotes or TomTom (there are others too), those addons will taint the map in the same way as the zoom settings.  So if you use other map addons, it makes no difference whether you have the zoom section settings enabled or not because the map will be tainted by those other addons anyway.

If the map is tainted, the following may occur:

- Attempting to click a quest link or quest item in the objective tracker might fail if the map is tainted.  If you are prevented from clicking a quest link or quest item in the objective tracker, you need to reload your UI to fix it.
- Premade group finder can show an error when you try to create a Mythic+ dungeon group with a keystone in your bag if the map is tainted.  LTM fixes this taint for player accounts with two-factor authentication (2FA) enabled but a side-effect of the fix is that the game no longer sets the dungeon title to the keystone level automatically (so you need to type in the level manually).  For players without 2FA, there is no fix so players without 2FA will continue to see errors if the map is tainted.
- If you create a dungeon group with premade group finder then attempt to edit the dungeon group and toggle the 'Limit to opposite faction' checkbox, you might see an error stopping you from doing that if the map is tainted.  Again, LTM gets around this by preventing you from toggling that particular checkbox while your group is listed (you can still toggle the checkbox while the group is unlisted though).
- The premade group finder report player function might not work if the map is tainted.  If you are prevented from reporting a player in premade group finder, you need to reload your UI to fix it.
- You might not be able to click map boss buttons (the ones on dungeon maps that link to the encounter journal) during combat if the map is tainted.  There is no workaround in LTM for this.
- Clicking on dungeon and raid location icons in the world map while the map is tainted might show an error instead of the encounter journal.  If you use the enhance dungeon icons setting in LTM, it prevents you from clicking dungeon and raid icons in combat to avoid this problem.

None of these issues affect the Classic map (BCC and Classic Era).  These issues are solely related to Shadowlands.

**Comment by leatrix** [comment]
> I might be wrong but I think certain UI elements such as hovering over the map to highlight a zone do not properly work when they are scaled up/down because the elements dont scale with the map.

LTM includes a fix for that.  In the latest release, you need to have Scale the map enabled (in older releases, you needed to have Unlock map frame enabled).  With scale the map enabled, you should be able to scale the quest map and the maximised map as you wish and area highlighting should work fine with any UI scale.

**Comment by Difjob** [comment]
Thanks for the very detailed reply, leatrix. I've never encountered any of those issues. I also only ever use the quest map.

**Comment by leatrix** [comment]
Here's an easy way to taint the map for a character that has not completed the Mor'geth world quest so that you can see the consequences of the taint.  This isn't the only way to taint the map.  There are many ways.  This is just something you can follow that will taint the map.

**Prerequisites**

- Disable all other addons except LTM to ensure they don't interfere.
- Login to a character that has the Mor'geth quest available on The Maw map.
- Enable **Set map scale** in LTM.
- Reload your UI with **/reload** to ensure nothing you have done interferes.  Don't reload your UI again for the remainder of the steps.

**Steps to taint the map**
- Enter combat and stay in combat for the remaining steps (just ensure your character is getting hit by a level 1 creature or something).
- Open the map (with either L or M keys) and navigate to The Maw zone.
- You will see the purple Mor'geth world quest icon on the map.
- Hold down shift and left-click the Mor'geth quest icon 4 times (just once is not enough) to toggle quest tracking for the quest twice.
- If the Mor'geth world quest is not showing in your objective tracker, click the icon once more so that the quest is now showing in the objective tracker.
- Left-click the Find Group button next to the Mor'geth quest in the objective tracker.  You will see an error message in chat **Interface action failed because of an AddOn**.  
- The map is now tainted.

Now that the map is tainted (remember to remain in combat)...

- Open the map (if it isn't open already) and navigate to the Timeless Isle zone in Pandaria.  You will see the boss buttons on the map (for Xuen, Ordos, etc).  Click any of the boss buttons.  The Encounter Journal will fail to open.
- Press I to try to open Dungeon Finder.  It will fail.
- Leave combat and press I to open Dungeon Finder.  The Mor'geth quest is probably showing in the search box.  Click Back, click Dungeons and click Find a Group.  Scroll down the list of available groups and find one which is a boost advertisement.  Right-click the group listing and click Report Advertisement.  It will fail.

If you now disable **Scale the map** in LTM and ensure no other zoom settings are enabled and no other addons are enabled, reload your UI and repeat everything above again, the map will not be tainted and so all of the steps will work fine.

Now disable all addons except TomTom.  So TomTom should be the only addon enabled.  Now follow all the steps again except the step to enable Set map scale since LTM will also be disabled.  Even with only TomTom enabled, the map will be tainted again.  When you reach the step where you right-click a boost advertisement in Dungeon Finder, it will fail and Wow will complain that TomTom has been blocked.

It's the same story if you disable all addons except HandyNotes.

Other map addons may also taint the map.  Blizzard have never fixed it because the taint only affects players that use addons.

In LTM, you can prevent the map from being tainted by not using any of the settings in the Zoom section.  With other map addons, they might taint the map regardless of their settings.

If you enable the settings in the zoom section but you don't use premade group finder, don't click quests or quest items in the objective tracker and don't click boss buttons on the map (the buttons that would normally open the Encounter Journal), you may rarely or never see a taint error.
