### ISSUE TITLE
remember zoom level 

### ISSUE THREAD

**Issue by JumpyCraft** [leatrix/leatrix-maps#30]

**Comment by JumpyCraft** [comment]
I cant see the remember zoom level option. this a removed issue or a bug?

**Comment by JumpyCraft** [comment]
is this permanent or for the time beeing?

**Comment by leatrix** [comment]
The zoom settings are removed because of the issues with Blizzard's game code in Dragonflight.  If Blizzard were to fix those issues, the settings would return.  If they don't fix them, the settings will not return.  Based on experience, I'm not expecting Blizzard to fix the game code so for the time being, you should probably assume it's permanent.

Regarding setting the map scale, the main issue with that has been reported to Blizzard [here](https://github.com/Stanzilla/WoWUIBugs/issues/338) although it's not as if they didn't know about the problem for years already so I don't know if they will fix that and I'm not sure it will be enough anyway.

**Comment by Nillx** [comment]
I thought they fixed the map scale issue with 10.0.2 :( I miss having a smaller map not blocking the whole screen. 

Noticed that there is an addon that  scales down the map but i havent tested it https://www.curseforge.com/wow/addons/world-map-shrinker

**Comment by leatrix** [comment]
Blizzard's implementation of GetCursorPosition [still doesn't support non-standard map scaling](https://github.com/Stanzilla/WoWUIBugs/issues/338) and replacing GetCursorPosition taints the UI.  Looks like Map Shrinker tries to get around this by setting the map size rather than scale but doing this has its own problems.  It's very easy to taint the UI with Map Shrinker.

**Comment by Nillx** [comment]
I see, sucks that this is still an issue but oh well, hope one day they fix it.
