### ISSUE TITLE
Req: Add optional map scaling

### ISSUE THREAD

**Issue by rodalpho** [leatrix/leatrix-maps#31]
The map scaling primarily breaks people using default UI actionbars, which many of us don't. A competing addon, Mapster, added a switch to enable scaling at the users' own risk. I'd prefer to continue using LTM, perhaps you could do the same thing?

**Comment by leatrix** [comment]
LTM for Dragonflight no longer supports map scaling.  This is because Blizzard don't support map scaling so adding map scaling to an addon requires replacing a Blizzard function (GetCursorPosition).  Replacing that function taints the UI.  It has always tainted the UI but in Dragonflight, the taint is more servere so the map scaling option was removed along with the zoom options which also tainted the UI.

There is a ticket here about GetCursorPosition so we will have to wait and see if Blizzard fixes that particular function.
https://github.com/Stanzilla/WoWUIBugs/issues/338

**Comment by rodalpho** [comment]
I'm aware of the taint, as evidenced in my post. My request is to optionally allow users to scale the map anyway. I assume that's a WONTFIX given your response.
