### ISSUE TITLE
[Feature Request] Scale World Map Window

### ISSUE THREAD

**Issue by Brian853** [leatrix/leatrix-maps#40]
Leatrix maps is a lightweight addons with commonly used powerful functions. 
I like it very much.
Only one request, I need map zoom for hi-dpi screen. 
I remember this feature was available in version 9.x, can it be revived?

**Comment by leatrix** [comment]
It was removed in Dragonflight due to issues with the game code.  Those issues appear to have been resolved in a recent game update.

> 10.0.34.alpha.1 - 30th January 2023
> - The 'Scale the map' option has returned.  As before, you can set the scale of the windowed and maximised maps independently.

To install alpha releases with CurseForge App, right-click the addon in your addon list and change the release type to alpha.  You can change it back to release any time.
